version: '3.8'

services:
  cadastros-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cadastros-app
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://medApp:5433/postgres
      SPRING_DATASOURCE_USERNAME: usuario_master
      SPRING_DATASOURCE_PASSWORD: m3d4PP
    networks:
      - autenticador-network

networks:
  autenticador-network:
    external: true